name: DevOps React Front End App CI/CD 

on:
  push:
    branches:
      - main  # You can specify your main branch here

jobs:
  ecs-ci-cd:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Replace with your desired AWS region


    - name: Create Docker Build and Upload to ECR 
      run: | 
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s3c4l2m0
        docker build --build-arg REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }} -t smart-devops-frontend .
        docker tag smart-devops-frontend:latest public.ecr.aws/s3c4l2m0/smart-devops-frontend:latest
        docker push public.ecr.aws/s3c4l2m0/smart-devops-frontend:latest
